#!/usr/bin/env python3
"""
Test mail configuration by loading settings from common.env and sending a test email.
Tests SMTP connectivity, authentication, and mail delivery.

Usage:
    ./test_mail_config.py [--to email@example.com]
    
Exit codes:
    0 - Test successful
    1 - Configuration error
    2 - Connection error
    3 - Authentication error
    4 - Send error
"""

import os
import sys
import smtplib
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional


def load_env_file(env_path: Path) -> Dict[str, str]:
    """Load environment variables from .env file."""
    env_vars = {}
    
    if not env_path.exists():
        print(f"❌ Error: Config file not found: {env_path}", file=sys.stderr)
        sys.exit(1)
    
    with open(env_path, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            # Parse KEY=VALUE or KEY="VALUE"
            match = re.match(r'^([A-Z_]+)=(.*)$', line)
            if match:
                key, value = match.groups()
                # Remove quotes if present
                value = value.strip('"').strip("'")
                env_vars[key] = value
    
    return env_vars


def validate_config(config: Dict[str, str]) -> tuple[bool, list[str]]:
    """Validate that all required mail settings are present."""
    required = ['MAIL_SMTP_SERVER', 'MAIL_SMTP_PORT', 'MAIL_FROM', 'MAIL_TO', 'MAIL_USER', 'MAIL_PASSWORD']
    missing = [key for key in required if not config.get(key)]
    
    if missing:
        return False, missing
    
    return True, []


def mask_password(password: str) -> str:
    """Mask password for display."""
    if len(password) <= 4:
        return "****"
    return password[:2] + "*" * (len(password) - 4) + password[-2:]


def display_config(config: Dict[str, str]):
    """Display current mail configuration (with masked password)."""
    print("\n📧 Current Mail Configuration:")
    print("-" * 50)
    print(f"SMTP Server:  {config.get('MAIL_SMTP_SERVER', 'NOT SET')}")
    print(f"SMTP Port:    {config.get('MAIL_SMTP_PORT', 'NOT SET')}")
    print(f"From:         {config.get('MAIL_FROM', 'NOT SET')}")
    print(f"To:           {config.get('MAIL_TO', 'NOT SET')}")
    print(f"Username:     {config.get('MAIL_USER', 'NOT SET')}")
    
    password = config.get('MAIL_PASSWORD', '')
    if password:
        print(f"Password:     {mask_password(password)}")
    else:
        print(f"Password:     NOT SET")
    print("-" * 50)


def test_smtp_connection(config: Dict[str, str]) -> bool:
    """Test SMTP server connection."""
    print("\n🔌 Testing SMTP connection...", end=' ', flush=True)
    
    try:
        server = smtplib.SMTP(config['MAIL_SMTP_SERVER'], int(config['MAIL_SMTP_PORT']), timeout=10)
        server.quit()
        print("✅ Connected")
        return True
    except Exception as e:
        print(f"❌ Failed")
        print(f"   Error: {e}", file=sys.stderr)
        return False


def test_smtp_auth(config: Dict[str, str]) -> Optional[smtplib.SMTP]:
    """Test SMTP authentication and return authenticated connection."""
    print("🔐 Testing SMTP authentication...", end=' ', flush=True)
    
    try:
        server = smtplib.SMTP(config['MAIL_SMTP_SERVER'], int(config['MAIL_SMTP_PORT']), timeout=10)
        server.starttls()
        server.login(config['MAIL_USER'], config['MAIL_PASSWORD'])
        print("✅ Authenticated")
        return server
    except smtplib.SMTPAuthenticationError as e:
        print(f"❌ Authentication failed")
        print(f"   Error: {e}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"❌ Failed")
        print(f"   Error: {e}", file=sys.stderr)
        return None


def send_test_email(config: Dict[str, str], server: smtplib.SMTP, to_addr: Optional[str] = None) -> bool:
    """Send a test email."""
    recipient = to_addr or config['MAIL_TO']
    print(f"📨 Sending test email to {recipient}...", end=' ', flush=True)
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = config['MAIL_FROM']
        msg['To'] = recipient
        msg['Subject'] = f"EntropyWatcher Mail Test - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        
        body = f"""This is a test email from EntropyWatcher mail configuration test.

Configuration:
- SMTP Server: {config['MAIL_SMTP_SERVER']}:{config['MAIL_SMTP_PORT']}
- From: {config['MAIL_FROM']}
- To: {recipient}
- Sent at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

If you receive this email, your mail configuration is working correctly.

---
Generated by test_mail_config.py
"""
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Send email
        server.send_message(msg)
        print("✅ Sent")
        print(f"\n✨ Test email sent successfully to {recipient}")
        print(f"   Check your inbox to confirm delivery.")
        return True
        
    except Exception as e:
        print(f"❌ Failed")
        print(f"   Error: {e}", file=sys.stderr)
        return False


def main():
    """Main test routine."""
    # Parse arguments
    to_override = None
    if len(sys.argv) > 1:
        if sys.argv[1] in ['-h', '--help']:
            print(__doc__)
            sys.exit(0)
        elif sys.argv[1] == '--to' and len(sys.argv) > 2:
            to_override = sys.argv[2]
    
    # Find common.env
    script_dir = Path(__file__).parent.parent
    env_path = script_dir / 'common.env'
    
    print("🔍 EntropyWatcher Mail Configuration Test")
    print(f"   Loading config from: {env_path}")
    
    # Load and validate config
    config = load_env_file(env_path)
    
    valid, missing = validate_config(config)
    if not valid:
        print(f"\n❌ Configuration incomplete. Missing variables:", file=sys.stderr)
        for var in missing:
            print(f"   - {var}", file=sys.stderr)
        sys.exit(1)
    
    # Display config
    display_config(config)
    
    # Test connection
    if not test_smtp_connection(config):
        sys.exit(2)
    
    # Test authentication
    server = test_smtp_auth(config)
    if not server:
        sys.exit(3)
    
    # Send test email
    try:
        success = send_test_email(config, server, to_override)
        if not success:
            sys.exit(4)
    finally:
        server.quit()
    
    print("\n✅ All tests passed!")
    sys.exit(0)


if __name__ == '__main__':
    main()
